CREATE DATABASE MANTENIMIENTO

GO

USE MANTENIMIENTO

GO

CREATE TABLE ROLES(
	ID INT IDENTITY(1,1),
	NAMEROL VARCHAR(50) NOT NULL,
	NORMALIZEDNAMEROL VARCHAR(50) NOT NULL,
	STATEROLS BIT NOT NULL,
	CONSTRAINT PK_IDROLS PRIMARY KEY(ID)
)

GO

INSERT INTO ROLES(
	NAMEROL,
	NORMALIZEDNAMEROL,
	STATEROLS
) VALUES (
	'admin',
	'ADMIN',
	1
)

GO


CREATE TABLE USUARIOS(
	ID INT IDENTITY(1,1),
	USERNAME VARCHAR(15) NOT NULL,
	NORMALIZEDUSERNAME VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NORMALIZEDEMAIL VARCHAR(50) NOT NULL,
	EMAILCONFIRMED BIT NOT NULL,
	PASSWORDHASH VARCHAR(50) NULL DEFAULT 'ASDJKAS@#@!#KSD', --PASSWORD ENCRIPTED OPCIONAL
	PHONENUMBER VARCHAR(15) NULL,
	PHONENUMBERCONFIRMED BIT NOT NULL,
	TWOFACTORENABLED BIT NOT NULL,
	LOCKOUTEND DATE NULL DEFAULT '1999-01-01',
	LOCKOUTENABLED BIT NOT NULL,
	ACCESSFAILEDCOUNT INT NOT NULL,
	STATEUSER BIT NOT NULL,
	CONSTRAINT PK_IDUSERS PRIMARY KEY(ID)
)

GO

INSERT INTO USUARIOS(
	USERNAME,
	NORMALIZEDUSERNAME,
	EMAIL,
	NORMALIZEDEMAIL,
	EMAILCONFIRMED,
	PASSWORDHASH,
	PHONENUMBER,
	PHONENUMBERCONFIRMED,
	TWOFACTORENABLED,
	LOCKOUTEND,
	LOCKOUTENABLED,
	ACCESSFAILEDCOUNT,
	STATEUSER
) VALUES (
	'jherrera',
	'JHERRERA',
	'jeffrey.herrera@usap.edu',
	'JEFFREY.HERRERA@USAP.EDU',
	1,
	'AJHSLDJASKasjdasdasasENCRIPTED',
	'(504) 9943-1243',
	1,
	1,
	null,
	1,
	0,
	1
)

GO

CREATE TABLE TALLER(
	ID_TALLER INT IDENTITY(1,1),
	NOMBRE_TALLER VARCHAR(30) NOT NULL,
	PROPIETARIO_TALLER VARCHAR(50) NOT NULL,
	RUC VARCHAR(15) NULL,
	DIRECCION VARCHAR(30) NULL,
	TELEFONO VARCHAR(15) NULL,
	EMAIL NVARCHAR(40) NULL,
	PAGWEB NVARCHAR(30) NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOTALLER BIT NOT NULL,
	CONSTRAINT PK_IDTALLER PRIMARY KEY(ID_TALLER)
)

GO

INSERT INTO TALLER(
	NOMBRE_TALLER,
	PROPIETARIO_TALLER,
	DIRECCION, 
	TELEFONO, 
	EMAIL,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOTALLER
) VALUES(
	'AUTOPARTS TALLER', 
	'JACKSON MARTINEZ', 
	'COL. STYBIS, SAN PEDRO SULA', 
	'504-250-3234', 
	'taller1@autoparts.com',
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE VEHICULOS(
	ID_VEHICULO INT IDENTITY(1,1),
	NPLACA VARCHAR(11) NOT NULL,
	MARCA_VEHICULO VARCHAR(20) NOT NULL,
	TIPO_VEHICULO VARCHAR(15) NOT NULL,
	MODELO_VEHICULO VARCHAR(15) NOT NULL,
	COLOR_VEHICULO VARCHAR(9) NULL,
	KILOMETRAJE_VEHICULO BIGINT NULL,
	CILINDRAJE_VEHICULO BIGINT NULL,
	FINGRESO_VEHICULO DATE NULL DEFAULT '1999-01-01',
	NUMERO_VEHICULO INT NOT NULL,
	NUMERONEUMATICOS INT NOT NULL,
	CAPGALONES INT NULL,
	CONSUMO_CIUDAD VARCHAR(11) NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOVEHICULOS BIT NOT NULL,
	CONSTRAINT PK_IDVEHICULO PRIMARY KEY(ID_VEHICULO),
)

GO

INSERT INTO VEHICULOS(
	NPLACA,
	MARCA_VEHICULO,
	TIPO_VEHICULO,
	MODELO_VEHICULO,
	COLOR_VEHICULO,
	KILOMETRAJE_VEHICULO,
	CILINDRAJE_VEHICULO,
	NUMERO_VEHICULO,
	NUMERONEUMATICOS,
	CAPGALONES,
	CONSUMO_CIUDAD,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOVEHICULOS
) VALUES(
	'FA3 CJDAL',
	'TOYOTA',
	'DOBLE CABINA',
	'HILUX',
	'GRIS',
	80000,
	6,
	1,
	12,
	15,
	'120 GALONES',
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE MANTENIMIENTO(
	ID_MANT INT IDENTITY(1,1),
	NOMBRE_MANT VARCHAR(30) NOT NULL,
	FMANT DATE NULL DEFAULT '1999-01-01',
	FPROXIMANT DATE NULL DEFAULT '1999-01-01',
	COSTO MONEY NOT NULL,
	OBSERVACIONES VARCHAR(120) NULL DEFAULT 'NINGUNA',
	ID_VEHICULO INT NOT NULL,
	ID_TALLER INT NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOMANT BIT NOT NULL,
	CONSTRAINT PK_IDMANT PRIMARY KEY(ID_MANT),
	CONSTRAINT FK_TALLER FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER) ON DELETE CASCADE,
	CONSTRAINT FK_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO) ON DELETE CASCADE,
)

GO

INSERT INTO MANTENIMIENTO(
	NOMBRE_MANT,
	FMANT,
	FPROXIMANT,
	COSTO,
	OBSERVACIONES,
	ID_VEHICULO,
	ID_TALLER,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOMANT
) VALUES(
	'MANTENIMIENTO BOURNERS',
	'2021-04-19',
	'2021-05-19',
	1199.99,
	'REQUIERE CAMBIO DE CANDELAS EN EL PROXIMO MANTENIMIENTO',
	1,
	1,
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE REPUESTOS(
	CODREPUESTO VARCHAR(9) NOT NULL,
	NOMBRE_REP VARCHAR(30) NOT NULL,
	COSTO_REP MONEY NOT NULL,
	TIENEGARANTIA BIT NOT NULL,
	ESTADO BIT NOT NULL, --1:TRUE => ACTIVO, 0:FALSE => INACTIVO
	TIPOMATERIAL VARCHAR(30) NOT NULL,
	PROCEDENCIA VARCHAR(30) NULL DEFAULT 'JAPAN',
	ID_MANT INT NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOREP BIT NOT NULL,
	CONSTRAINT PK_REPUNIQUE PRIMARY KEY(CODREPUESTO, NOMBRE_REP),
	CONSTRAINT FK_MANTENIMIENTO FOREIGN KEY(ID_MANT) REFERENCES MANTENIMIENTO(ID_MANT) ON DELETE CASCADE
)

GO

INSERT INTO REPUESTOS(
	CODREPUESTO,
	NOMBRE_REP,
	COSTO_REP,
	TIENEGARANTIA,
	ESTADO,
	TIPOMATERIAL,
	PROCEDENCIA,
	ID_MANT,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOREP
) VALUES(
	'10001',
	'CANDELAS',
	1199.99,
	1,
	1,
	'IRIDIO Y PLATINO',
	'JAPAN',
	1,
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE NEUMATICOS(
	ID_NEU INT IDENTITY(1,1),
	CODNEUMATICO VARCHAR(11) NOT NULL,
	MARCA VARCHAR(18) NULL,
	PRECIO MONEY NOT NULL,
	TIENEGARANTIA BIT NOT NULL, -- 1: SI 0:NO
	DURACION VARCHAR(25) NULL,
	PRES_INFLA_CONCAR VARCHAR(13) NOT NULL, 
	PRES_INFLA_SINCAR VARCHAR(13) NOT NULL, 
	CARGAMAX VARCHAR(11) NULL,
	CANTIDAD INT NOT NULL,
	FENTREGA DATE NULL DEFAULT '1999-01-01',
	ID_VEHICULO INT NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADONEU BIT NOT NULL,
	CONSTRAINT PK_IDNEU PRIMARY KEY(ID_NEU),
	CONSTRAINT FK_VEHICULONEUMATICOS FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO)
)

GO

INSERT INTO NEUMATICOS(
	CODNEUMATICO,
	MARCA,
	PRECIO,
	TIENEGARANTIA,
	DURACION,
	PRES_INFLA_CONCAR,
	PRES_INFLA_SINCAR,
	CARGAMAX,
	CANTIDAD,
	FENTREGA,
	ID_VEHICULO,
	USUARIOCREACION,
	FECHACREACION,
	ESTADONEU
) VALUES(
	'NEU-001',
	'GO0D YEAR',
	1499.99,
	1,
	'1 A�O 5 DIAS 12 HORAS',
	'12 LB',
	'14 LB',
	'700 LB',
	10,
	'2021-01-01',
	1,
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE GENERO(
	ID INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(9) NOT NULL,
	ABREVIADO VARCHAR(1) NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	CONSTRAINT PK_IDGENERO PRIMARY KEY(ID)
)

GO

INSERT INTO GENERO(
	DESCRIPCION,
	ABREVIADO,
	USUARIOCREACION,
	FECHACREACION
) VALUES(
	'MASCULINO',
	'M',
	'jherrera',
	'2021-04-19'
), (
	'FEMENINO', 
	'F',
	'jherrera',
	'2021-04-19'
);

GO

CREATE TABLE CONDUCTORES(
	ID_COND INT IDENTITY(1,1),
	CI VARCHAR(15) NOT NULL, --0501-1999-02920
	NOMBRE VARCHAR(40) NOT NULL,
	APATERNO VARCHAR(25) NOT NULL, 
	AMATERNO VARCHAR(25) NOT NULL, 
	FINGRESO DATE NULL DEFAULT '1999-01-01',
	DIRECCION VARCHAR(120) NULL DEFAULT 'NINGUNA',
	ID_GENERO INT NOT NULL,
	NACIONALIDAD VARCHAR(15) NOT NULL,
	TELEFONO VARCHAR(15) NULL,
	CELULAR VARCHAR(15) NULL, 
	ESTADO BIT NOT NULL, --0: FALSE, 1: TRUE
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOCONDU BIT NOT NULL,
	CONSTRAINT UQ_CI UNIQUE(CI),
	CONSTRAINT PK_IDCOND PRIMARY KEY(ID_COND),
	CONSTRAINT FK_GENERO FOREIGN KEY(ID_GENERO) REFERENCES GENERO(ID)
)

GO

INSERT INTO CONDUCTORES(
	CI,
	NOMBRE,
	APATERNO,
	AMATERNO,
	FINGRESO,
	DIRECCION,
	ID_GENERO,
	NACIONALIDAD,
	TELEFONO,
	CELULAR,
	ESTADO,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOCONDU
) VALUES(
	'0501-1999-02391',
	'JARVIS ALEJANDRO',
	'FORD',
	'JITSUN',
	'2021-01-01',
	NULL,
	1,
	'HONDURE�A',
	'(504) 2176-213',
	'(504) 9932-3413',
	1,
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE SALIDAS(
	NUMSALIDA INT IDENTITY(1,1) NOT NULL,
	LSALIDA VARCHAR(30) NULL, 
	LDESTINO VARCHAR(30) NULL, 
	NPERSONAS INT NULL, 
	COSTO MONEY NOT NULL,
	ASUNTO VARCHAR(15) NULL,
	FSALIDA DATE NULL DEFAULT '1999-01-01',
	FRETORNO DATE NULL DEFAULT '1999-01-01',
	ID_COND INT NOT NULL,
	ID_VEHICULO INT NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOSAL BIT NOT NULL,
	CONSTRAINT PK_IDSALIDAS PRIMARY KEY(NUMSALIDA),
	CONSTRAINT FK_VEHICULOSALIDAS FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO),
	CONSTRAINT FK_CONDSALIDAS FOREIGN KEY(ID_COND) REFERENCES CONDUCTORES(ID_COND),
)

GO

INSERT INTO SALIDAS(
	LSALIDA,
	LDESTINO,
	NPERSONAS,
	COSTO,
	ASUNTO,
	FSALIDA,
	FRETORNO,
	ID_COND,
	ID_VEHICULO,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOSAL
) VALUES(
	'TONCONTIN',
	'AREVALO CITY',
	5,
	1199.99,
	'URGENTE',
	'2021-04-19',
	'2021-04-23',
	1,
	1,
	'jherrera',
	'2021-04-19',
	1
);


GO

CREATE TABLE DENTREGAV(
	IDENTREGAV INT IDENTITY(1,1),
	FRECEPCION DATE NULL DEFAULT '1999-01-01',
	ID_VEHICULO INT NOT NULL,
	ID_COND INT NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADODENTRE BIT NOT NULL,
	CONSTRAINT PK_IDENTREGAV PRIMARY KEY(IDENTREGAV),
	CONSTRAINT FK_VEHICULOENTREGA FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO),
	CONSTRAINT FK_CONDUCTORES FOREIGN KEY(ID_COND) REFERENCES CONDUCTORES(ID_COND),
)

GO

INSERT INTO DENTREGAV(
	FRECEPCION,
	ID_VEHICULO,
	ID_COND,
	USUARIOCREACION,
	FECHACREACION,
	ESTADODENTRE
) VALUES(
	'2021-04-19',
	1,
	1,
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE INCIDENTES(
	IDINCIDENTE INT IDENTITY(1,1),
	TIPO_INCIDENTE VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR(30) NULL,
	GASTO_INCIDENTE MONEY NOT NULL,
	FINCIDENTE DATE NULL DEFAULT '1999-01-01',
	ID_COND INT NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOINCID BIT NOT NULL,
	CONSTRAINT PK_IDINCIDENTS PRIMARY KEY(IDINCIDENTE),
	CONSTRAINT FK_CONDUCTOR FOREIGN KEY(ID_COND) REFERENCES CONDUCTORES(ID_COND)
)

GO

INSERT INTO INCIDENTES(
	TIPO_INCIDENTE,
	DESCRIPCION,
	GASTO_INCIDENTE,
	FINCIDENTE,
	ID_COND,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOINCID
) VALUES (
	'CHOQUE',
	'PARTE FRONTAL',
	3599.99,
	'2021-04-19',
	1,
	'jherrera',
	'2021-04-19',
	1
);

GO

CREATE TABLE DETALLECONSUMO(
	IDCONSUMO INT IDENTITY(1,1),
	ID_VEHICULO INT NOT NULL,
	ID_COND INT NOT NULL,
	NOMBRECOMB VARCHAR(30) NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHACONSUMO DATE NULL DEFAULT '1999-01-01',
	NOMBREESTACION VARCHAR(30) NOT NULL,
	USUARIOCREACION VARCHAR(15) NULL,
	FECHACREACION DATE NULL,
	USUARIOMODIFICACION VARCHAR(15) NULL,
	FECHAMODIFICACION DATE NULL,
	ESTADOCONSUM BIT NOT NULL,
	CONSTRAINT PK_IDCONSUMO PRIMARY KEY(IDCONSUMO),
	CONSTRAINT FK_VEHICULOCONSUMO FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO) ON DELETE CASCADE,
	CONSTRAINT FK_CONDUCTORCONSUMO FOREIGN KEY(ID_COND) REFERENCES CONDUCTORES(ID_COND) ON DELETE CASCADE
)

INSERT INTO DETALLECONSUMO(
	ID_VEHICULO,
	ID_COND,
	NOMBRECOMB,
	CANTIDAD,
	FECHACONSUMO,
	NOMBREESTACION,
	USUARIOCREACION,
	FECHACREACION,
	ESTADOCONSUM
) VALUES(
	1,
	1,
	'NO SE A QUE SE REFIERE JAJA',
	7,
	'2021-04-19',
	'ESTACION NORTE',
	'jherrera',
	'2021-04-19',
	1
);

SELECT * FROM VEHICULOS

SELECT * FROM MANTENIMIENTO

SELECT * FROM TALLER
